version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: datatube
    # volumes:
    #   - ./server/mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - database_net
  api:
    build: 
      context: ./server
    depends_on:
      - db
    networks:
      - database_net
      - api_net
    environment:
      DB_USER: root
      DB_PASSWORD: rootpwd
      DB_HOST: db
      DB_SCHEMA: datatube
      YOUTUBE_API_KEY: $YOUTUBE_API_KEY

  front:
    build: 
      context: ./client
    networks:
      - api_net
networks:
  database_net:
  api_net:
