version: "3.7"
services:
  db:
    image: '{{ site_docker_namespace }}/{{ site_db_image_environment }}:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '{{ site_db_pwd }}'
    networks:
      - database_net
  api:
    image: '{{ site_docker_namespace }}/{{ site_api_image_environment }}:latest'
