version: "3.3"
services:
  db:
    image: '{{ site_docker_namespace }}/{{ site_db_image_environment }}:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '{{ site_db_pwd }}'
    networks:
      - database_net
  api:
    image: '{{ site_docker_namespace }}/{{ site_api_image_environment }}:latest'
    depends_on:
      - db
    networks:
      - database_net
      - api_net
    environment:
      DB_USER: '{{ site_db_user }}'
      DB_PASSWORD: '{{ site_db_pwd }}'
      DB_HOST: db
      DB_SCHEMA: '{{ site_db_schema }}'
      YOUTUBE_API_KEY: '{{ site_api_yt_key }}'
    ports:
      - '{{ site_api_port }}:3000'
  client:
    image: '{{ site_docker_namespace }}/{{ site_client_image_environment }}:latest' 
    restart: always
    ports:
      - '{{ site_client_port }}:80'
    depends_on:
      - api
    networks:
      - api_net
networks:
  database_net:
  api_net:
